export const EXCLUDED_DECIMAL_FIELDS = [
    'rawMaterials.shelfLife',
    'shelfLife',
    'leadTime',
    'amount',
    'palletCount',
    'lotNo',
    'bagNo',
    'submissionId',
    'id',
    'step',
    'sequence',
    'date',
    'number',
    'tempPoint3',
    'tempPoint2', 
    'tempPoint1', 
    'naclWaterSpecGrav',
    'temperature',
    'temp',
    'nacl15SpecGrav',
    'calculations.nacl15SpecGrav',
    'no',
    'qty'

];